### PR TITLE
Enable to fix nodes

### PR DESCRIPTION
**Pull request by Golbstein**

### CODE REVIEW

**Comment by JeffLIrion** [comment]
The linting check is currently failing. The unit tests and coverage check also need to pass.

**Comment by Golbstein** [comment]
> The linting check is currently failing. The unit tests and coverage check also need to pass.

Probably because you must fix at least one node..

**Comment by JeffLIrion** [comment]
I fixed the linting check, but there are failing unit tests.

**Comment by JeffLIrion** [comment]
I merged https://github.com/JeffLIrion/python-graphslam/pull/25/files instead.

**Pull request closed without merging**
